# Creating matrices
You can pass Python lists of lists to create a 2-D array (or “matrix”) to represent them in NumPy.

In [3]:
import numpy as np

In [4]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
# Indexing and slicing operations are useful when you’re manipulating matrices:

print(data[0, 1]) # coordinates of an element in the matrix
print(data[1:3]) # 0th index is [1, 2] 1st is [3, 4] 2nd is [5, 6]
print(data[0:2, 0]) # 

2
[[3 4]
 [5 6]]
[1 3]


In [6]:
# You can aggregate matrices the same way you aggregated vectors:

print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [7]:
# You can aggregate all the values in a matrix and you can aggregate them across columns or rows using the axis parameter.
# To illustrate this point, let’s look at a slightly modified dataset:
data = np.array([[1, 2], [5, 3], [4, 6]])
data
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 5 6]


In [8]:
# Once you’ve created your matrices, you can add and multiply them using arithmetic operators 
# if you have two matrices that are the same size.

data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [11]:
# You can do these arithmetic operations on matrices of different sizes, 
# but only if one matrix has only one column or one row. 
# In this case, NumPy will use its broadcast rules for the operation.

data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [12]:
# Be aware that when NumPy prints N-dimensional arrays, 
# the last axis is looped over the fastest while the first axis is the slowest. For instance:

np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [14]:
# There are often instances where we want NumPy to initialize the values of an array. 
# NumPy offers functions like ones() and zeros(), and the random.Generator class for random number generation for that.
# All you need to do is pass in the number of elements you want it to generate:

print(np.ones(3))
print(np.zeros(3))
rng = np.random.default_rng()  # the simplest way to generate random numbers
rng.random(3) 

[1. 1. 1.]
[0. 0. 0.]


array([0.79871097, 0.59813518, 0.15034311])

In [16]:
# You can also use ones(), zeros(), and random() to create a 2D array,
# if you give them a tuple describing the dimensions of the matrix:

print(np.ones((3, 2)))
print(np.zeros((3, 2)))
rng.random((3, 2)) 

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


array([[0.73097507, 0.63821513],
       [0.7621578 , 0.41849261],
       [0.86396837, 0.95014783]])