# Creating matrices
You can pass Python lists of lists to create a 2-D array (or “matrix”) to represent them in NumPy.

In [1]:
import numpy as np

In [2]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# Indexing and slicing operations are useful when you’re manipulating matrices:

print(data[0, 1]) # coordinates of an element in the matrix
print(data[1:3]) # 0th index is [1, 2] 1st is [3, 4] 2nd is [5, 6]
print(data[0:2, 0]) # 

2
[[3 4]
 [5 6]]
[1 3]


In [4]:
# You can aggregate matrices the same way you aggregated vectors:

print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [6]:
# You can aggregate all the values in a matrix and you can aggregate them across columns or rows using the axis parameter.
# To illustrate this point, let’s look at a slightly modified dataset:
data = np.array([[1, 2], [5, 3], [4, 6]])
data
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 5 6]


In [7]:
# Once you’ve created your matrices, you can add and multiply them using arithmetic operators 
# if you have two matrices that are the same size.

data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])