# How to get unique items and counts

This section covers np.unique()

You can find the unique elements in an array easily with np.unique.

In [2]:
import numpy as np

In [3]:
# For example, if you start with this array:

a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [4]:
# you can use np.unique to print the unique values in your array:

unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [5]:
# To get the indices of unique values in a NumPy array (an array of first index positions of unique values in the array), 
# just pass the return_index argument in np.unique() as well as your array.

unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [6]:
# You can pass the return_counts argument in np.unique() 
# along with your array to get the frequency count of unique values in a NumPy array.

unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [ ]:
# This also works with 2D arrays! If you start with this array:

a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [8]:
# You can find unique values with:

unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


If the axis argument isn’t passed, your 2D array will be flattened.

If you want to get the unique rows or columns, make sure to pass the axis argument. To find the unique rows, specify axis=0 and for columns, specify axis=1.

In [10]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)
unique_columns = np.unique(a_2d, axis=1)
print(unique_columns)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]


In [13]:
# All at Once
# To get the unique rows, index position, and occurrence count, you can use:

unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)
print(indices) # First row 0th index second row 1st and thirs row 2nd index
print(occurrence_count) # First row occurred twice and other two once therefore [2 1 1]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]
