# Transposing and reshaping a matrix

This section covers arr.reshape(), arr.transpose(), arr.T

-> It’s common to need to transpose your matrices. NumPy arrays have the property T that allows you to transpose a matrix.

-> You may also need to switch the dimensions of a matrix. This can happen when, for example, you have a model that expects a certain input shape that is different from your dataset. This is where the reshape method can be useful. You simply need to pass in the new dimensions that you want for the matrix.

In [1]:
import numpy as np

In [4]:
data = np.arange(6)

print(data.reshape(3, 2))
print(data.reshape(2, 3))

[[0 1]
 [2 3]
 [4 5]]
[[0 1 2]
 [3 4 5]]


In [6]:
# You can also use .transpose() to reverse or change the axes of an array according to the values you specify.

#using this array:
arr = np.arange(6).reshape((2, 3))
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [7]:
# You can also use arr.T:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])