# How to reverse an array

This section covers np.flip()

NumPy’s np.flip() function allows you to flip, or reverse, the contents of an array along an axis. When using np.flip(), specify the array you would like to reverse and the axis. If you don’t specify the axis, NumPy will reverse the contents along all of the axes of your input array.

## Reversing a 1D array

In [1]:
import numpy as np

In [2]:
# If you begin with a 1D array like this one:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])   

In [5]:
# You can reverse this array(arr) with:

reversed_arr = np.flip(arr)

# if you want to print your reversed array:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


## Reversing a 2D array

In [9]:
# A 2D array works much the same way.
# If you start with this array:

arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
# You can reverse the content in all of the rows and all of the columns with:

reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [ ]:
# You can reverse only the rows with:

reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [ ]:
# You can reverse only the rows with: 

reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

In [ ]:
# You can also reverse the contents of only one column or row. 
# For example, you can reverse the contents of the row at index position 1 (the second row):

arr_2d[1] = np.flip(arr_2d[1]) # just reversing row 1 or changing row 1 of arr_2d with it's reverse
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [11]:
# You can also reverse the column at index position 1 (the second column):

arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]
