# Reshaping and flattening multidimensional arrays

This section covers .flatten(), ravel()

There are two popular ways to flatten an array: .flatten() and .ravel(). The primary difference between the two is that the new array created using ravel() is actually a reference to the parent array (i.e., a “view”). This means that any changes to the new array will affect the parent array as well. Since ravel does not create a copy, it’s memory efficient.

In [2]:
import numpy as np


In [ ]:
# If you start with this array:

x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [4]:
# You can use flatten to flatten your array into a 1D array.

x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
# When you use flatten, changes to your new array won’t change the parent array.

# For example:

a1 = x.flatten()
a1[0] = 99
print(x)  # Original array
print(a1)  # New array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# But when you use ravel, the changes you make to the new array will affect the parent array.

# For example:

a2 = x.ravel() # .ravel() does not make a copy, therefore original array gets changed like new one
a2[0] = 98
print(x)  # Original array
print(a2)  # New array

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]
