# fundamentals

In [53]:
# To install numpy
# pip install numpy

In [ ]:
# Improrting numpy after installation
import numpy as np

### Initializing a 1D Array using list  

In [ ]:
a = np.array([1,2,3,4,5,6]) # array initialized
a 

array([1, 2, 3, 4, 5, 6])

In [62]:
print(a)
a[0] = 10
a

[1 2 3 4 5 6]


array([10,  2,  3,  4,  5,  6])

### Accessing elements through Indexing and Slicing

In [63]:
a[:3]

array([10,  2,  3])

In [ ]:
b = a[3:]
b
b[0] = 40  # (b) view: an object(b) that refers to the data in the original array(a)
a

array([10,  2,  3, 40,  5,  6])

### Two- and higher-dimensional arrays can be initialized from nested Python sequences

In [65]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [67]:
# element of the array can be accessed by specifying the index along each axis within a single set of square brackets, 
# separated by commas. For instance, the element 8 is in row 1 and column 3
a[1, 3]

8