### How to create a basic array : This section covers np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()

In [ ]:
# import numpy as np

In [7]:
# Besides creating an array from a sequence of elements, you can easily create an array filled with 0’s:

print(np.zeros(5))
print(np.zeros(1))
print(np.zeros(2))

[0. 0. 0. 0. 0.]
[0.]
[0. 0.]


In [12]:
# Or an array filled with 1’s:
print(np.ones(5))
print(np.ones(2))
print(np.ones(0))

[1. 1. 1. 1. 1.]
[1. 1.]
[]


In [21]:
# The function empty creates an array whose initial content is random and depends on the state of the memory. 
# The reason to use empty over zeros (or something similar) is speed.

print(np.empty(2)) # Create an empty array with 2 elements
print(np.empty(5))
print(np.empty(0))

# make sure to fill every element afterwards

[1. 1.]
[1. 1. 1. 1. 1.]
[]


In [26]:
# create an array with a range of elements

print(np.arange(4))

# And even an array that contains a range of evenly spaced intervals. 
# To do this, you will specify the first number, last number, and the step size.

np.arange(2, 9, 2) # first no., last no. and the step size or jump size 

[0 1 2 3]


array([2, 4, 6, 8])

In [28]:
# np.linspace() to create an array with values that are spaced linearly in a specified interval

np.linspace(0, 10, num=5) # same as arange but here in place of step you provide "the no. of elemnts you want"

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [32]:
# Specifying your data type

# While the default data type is floating point (np.float64), 
# you can explicitly specify which data type you want using the dtype keyword.

x = np.ones(2, dtype=np.int64) # defining data type by our own
x

array([1, 1], dtype=int64)