### Sorting and Concatenation of Elements
This section covers np.sort(), np.concatenate()

In [17]:
import numpy as np

In [3]:
# Sorting an array is simple with np.sort(). 
# You can specify the axis, kind, and order when you call the function


arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [4]:
# you can quickly sort the array using :
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In addition to sort, which returns a sorted copy of an array, you can use:

1. argsort, which is an indirect sort along a specified axis,

2. lexsort, which is an indirect stable sort on multiple keys,

3. searchsorted, which will find elements in a sorted array, and

4. partition, which is a partial sort.

## Concatenation

In [7]:
a = np.array([1, 9, 3, 4])
b = np.array([5, 6, 7, 8])

In [10]:
# you can concatenate both these arrays using :
c = np.concatenate((a, b))
c

array([1, 9, 3, 4, 5, 6, 7, 8])

In [13]:
# sorting the above concatenated array
np.sort(c)

array([1, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# For multidimensional arrays
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [16]:
# concatenating them using :
np.concatenate((x, y), axis=0)

# this axis = 0 represents the row dimension, means concateneate along the axis 0 i.e(row wise)

array([[1, 2],
       [3, 4],
       [5, 6]])