### shape and size of an array

This section covers ndarray.ndim, ndarray.size, ndarray.shape

In [1]:
import numpy as np

In [3]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [4]:
array_example.ndim 
# will tell you the number of axes, or dimensions, of the array.

3

In [5]:
array_example.size 
# will tell you the total number of elements of the array. 
# This is the product of the elements of the array’s shape.

24

In [6]:
array_example.shape 
# will display a tuple of integers that indicate the number of elements stored along each dimension of the array.
#  If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

(3, 2, 4)

### Can you reshape an array?

This section covers arr.reshape()


Yes!

Using arr.reshape() will give a new shape to an array without changing the data. Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.

In [7]:
# like initializing an array :
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [11]:
# You can use reshape() to reshape your array. 
# For example, you can reshape this array to an array with three rows and two columns
print(a.reshape(2,3))

[[0 1 2]
 [3 4 5]]


In [10]:
print(a.reshape(3,2))

[[0 1]
 [2 3]
 [4 5]]


In [15]:
# you can also provide few parameters while using reshape() method
np.reshape(a, (1, 6), order='C')

# this (1,6) is the shape you want to reshape your array

array([[0, 1, 2, 3, 4, 5]])

a is the array to be reshaped.

shape is the new shape you want. You can specify an integer or a tuple of integers. If you specify an integer, the result will be an array of that length. The shape should be compatible with the original shape.

order: C means to read/write the elements using C-like index order, F means to read/write the elements using Fortran-like index order, A means to read/write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise. (This is an optional parameter and doesn’t need to be specified.)