### Indexing and slicing

In [2]:
import numpy as np

In [3]:
data = np.array([1, 2, 3])

print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

2
[1 2]
[2 3]
[2 3]


You may want to take a section of your array or specific array elements to use in further analysis or additional operations. To do that, you’ll need to subset, slice, and/or index your arrays.

If you want to select values from your array that fulfill certain conditions, it’s straightforward with NumPy.

In [4]:
# for example let's start with this array
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a.shape
a.size
a.ndim


2

In [5]:
# printing all the values that are less than five 
print(a[a < 5])

[1 2 3 4]


In [6]:
# You can also select, for example, numbers that are equal to or greater than 5, and use that condition to index an array.
five_up = (a >= 5)
print(a[five_up])

five_up = a[a >= 5]
print(five_up)

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [7]:
divisible_by_2 = a[a%2 ==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [8]:
# you can select elements that satisfy two conditions using the & and | operators:

c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


You can also make use of the logical operators & and | in order to return boolean values that specify whether or not the values in an array fulfill a certain condition. This can be useful with arrays that contain names or other categorical values.

In [9]:
five_up = (a > 5) | (a == 5)
# five_up = a[(a > 5) | (a == 5)]
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


## Indexing

In [10]:
# you can also use np.nonzero() to select elements or indices from an array
# starting with this array 
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [11]:
# You can use np.nonzero() to print the indices of elements that are, for example, less than 5:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In this example, a tuple of arrays was returned: one for each dimension. The first array represents the row indices where these values are found, and the second array represents the column indices where the values are found.

## ZIP function

If you want to generate a list of coordinates where the elements exist, you can zip the arrays, iterate over the list of coordinates, and print them. For example:

In [13]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [15]:
# here basically we are accessing elements of an array as same as we do in array like a[b] where a=array, b=index
print(a[b])


[1 2 3 4]


If the element you’re looking for doesn’t exist in the array, then the returned array of indices will be empty. For example:

In [16]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))
