### How to create an array from existing data

This section covers slicing and indexing, np.vstack(), np.hstack(), np.hsplit(), .view(), copy()



In [3]:
import numpy as np

In [4]:
# let's take an array say :
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# You can create a new array from a section of your array any time by specifying where you want to slice your array.

arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [6]:
# You can also stack two existing arrays, both vertically and horizontally. Let’s say you have two arrays, a1 and a2:

a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [7]:
# You can stack them vertically with vstack:

np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [8]:
# stack them horizontally with hstack:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

## Split Array 

In [9]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
# If you wanted to split this array into three equally shaped arrays, you should run:

np.hsplit(x, 3)

# Basic funda is just get the no. of elements/size of the array and the no. of splits you want,
# just see if the total is divisible by that no.

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

### Splitting After particular column

In [ ]:
# If you want to split your array after the third and fourth column, you can run:

np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

### .view() and copy()

You can use the view method to create a new array object that looks at the same data as the original array (a shallow copy).

Views are an important NumPy concept. NumPy functions, as well as operations like indexing and slicing, will return views whenever possible. This saves memory and is faster (no copy of the data has to be made). However it’s important to be aware of this - modifying data in a view also modifies the original array!

In [12]:
# let's say you create this array:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [17]:
# Now we create an array b1 by slicing a and modify the first element of b1. 
# This will modify the corresponding element in a as well

b1 = a[0, :]
b1
b1[0] = 99
b1
# b1 is a view here
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
# Using the copy method will make a complete copy of the array and its data (a deep copy). 
# To use this on your array, you could run:

b2 = a.copy
